/**
 * Planner markdown parser.
 *
 * Reads the PlannerAgent's `07-tasks.md` and extracts a list of structured
 * tasks. The parser is intentionally permissive: it must accept the
 * Planner's free-form markdown output (which is itself generated by an
 * LLM in a later milestone) and produce a normalized TaskRecord array.
 *
 * Expected shape (per personas/planner.md):
 *
 *   # Implementation Plan — <title>
 *
 *   ## File Structure Plan
 *   ...
 *
 *   ## Tasks
 *
 *   ### T001 — <imperative title>
 *   **File(s)**: `path1` (action1), `path2` (action2)
 *   **Depends on**: T000 (or "none")
 *   **Estimated**: <n> min
 *
 *   #### Step 1: Write the failing test (RED)
 *   - File: `<test path>`
 *   - Test name: `<describe block>`
 *   - Assertion: <exact assertion text>
 *
 *   #### Step 2: Verify RED
 *   - Run: `<command>`
 *   - Expected: FAIL with "<expected failure reason>"
 *
 *   #### Step 3: Minimal implementation (GREEN)
 *   - File: `<src path>`
 *   - Change: <one sentence>
 *
 *   #### Step 4: Verify GREEN
 *   - Run: `<command>`
 *   - Expected: PASS; full suite still green; no warnings
 *
 *   #### Step 5: Commit
 *   - Message: `<type>(<scope>): <subject>`
 *
 *   ## Execution Order
 *   T001 → T002 → ...
 *
 * The parser does NOT validate that the markdown follows PL-5 (no
 * placeholders). That is the PlannerAgent's responsibility. The parser
 * just extracts what is there and marks anything it cannot parse with a
 * `parseWarning` so the orchestrator can surface it.
 */
export interface ParsedPlannerTask {
  taskId: string
  title: string
  files: string[]
  dependsOn: string[]
  estimatedMinutes?: number
  red?: { file: string; testName: string; assertion: string }
  green?: { file: string; change: string }
  verify?: { run: string; expectedPass: boolean }
  commit?: { type: string; scope: string; subject: string }
  parseWarnings: string[]
}

/**
 * Parse the body of `07-tasks.md` into a list of structured tasks.
 *
 * The function is forgiving:
 *   - Missing `### TXXX` sections are ignored.
 *   - Missing sub-steps become `undefined` in the returned task; the
 *     orchestrator treats that as "step not specified" and surfaces it.
 *   - Bad quoting on File/Run/etc. lines falls back to a literal read.
 */
export function parsePlannerMarkdown(markdown: string): ParsedPlannerTask[] {
  const tasks: ParsedPlannerTask[] = []

  // Split on task headers. Each chunk starts at `### TXXX —` and runs to
  // the next `### TYYY —` or the next `## ` section or EOF.
  const taskHeaderRegex = /^###\s+(T\d{3,})\b[^\n]*$/gm
  const headerMatches = [...markdown.matchAll(taskHeaderRegex)]
  for (let i = 0; i < headerMatches.length; i++) {
    const start = headerMatches[i].index!
    const end =
      i + 1 < headerMatches.length ? headerMatches[i + 1].index! : markdown.length
    const block = markdown.slice(start, end)
    tasks.push(parseTaskBlock(headerMatches[i][1], block))
  }

  return tasks
}

function parseTaskBlock(taskId: string, block: string): ParsedPlannerTask {
  const warnings: string[] = []

  // The header itself contains the title: `### T001 — <imperative title>`
  const headerLine = block.split('\n', 1)[0]
  const titleMatch = headerLine.match(/^###\s+T\d{3,}\s*[—–-]\s*(.+?)\s*$/)
  const title = titleMatch ? titleMatch[1] : headerLine

  // File(s): `<path>` (action), `<path>` (action), ...
  const filesLine = findKvLine(block, 'File(s)') ?? findKvLine(block, '**File(s)**')
  const files: string[] = []
  if (filesLine) {
    // Split on backtick boundaries; we only care about paths.
    const pathMatches = filesLine.match(/`([^`]+)`/g) ?? []
    for (const m of pathMatches) {
      files.push(m.replace(/`/g, '').trim())
    }
    if (files.length === 0) warnings.push('files: could not parse any file path')
  } else {
    warnings.push('files: missing File(s) line')
  }

  // Depends on
  const dependsLine = findKvLine(block, 'Depends on') ?? 'none'
  const dependsOn: string[] = []
  if (dependsLine && !/^none$/i.test(dependsLine.trim())) {
    dependsOn.push(
      ...dependsLine
        .split(/[,\s]+/)
        .map((s) => s.trim())
        .filter((s) => /^T\d{3,}$/.test(s)),
    )
  }

  // Estimated
  const estimatedLine = findKvLine(block, 'Estimated')
  let estimatedMinutes: number | undefined
  if (estimatedLine) {
    const m = estimatedLine.match(/(\d+)\s*min/i)
    estimatedMinutes = m ? parseInt(m[1], 10) : undefined
  }

  // Step 1: Write the failing test (RED)
  const redBlock = extractStepBlock(block, /Step 1:[^\n]*RED/i)
  const red = redBlock ? parseRedStep(redBlock, warnings) : undefined

  // Step 3: Minimal implementation (GREEN)
  const greenBlock = extractStepBlock(block, /Step 3:[^\n]*GREEN/i)
  const green = greenBlock ? parseGreenStep(greenBlock, warnings) : undefined

  // Step 4: Verify GREEN
  const verifyBlock = extractStepBlock(block, /Step 4:[^\n]*Verify GREEN/i)
  const verify = verifyBlock ? parseVerifyStep(verifyBlock, warnings) : undefined

  // Step 5: Commit
  const commitBlock = extractStepBlock(block, /Step 5:[^\n]*Commit/i)
  const commit = commitBlock ? parseCommitStep(commitBlock, warnings) : undefined

  return {
    taskId,
    title,
    files,
    dependsOn,
    estimatedMinutes,
    red,
    green,
    verify,
    commit,
    parseWarnings: warnings,
  }
}

/**
 * Find a `Key: value` line that may or may not be wrapped in `**` and that
 * may span the whole line.
 */
function findKvLine(block: string, key: string): string | null {
  const lines = block.split('\n')
  for (const line of lines) {
    // Strip ALL bold markers (`**...**` inline), not just at line edges, so
    // a line like `**Depends on**: T001` and `Depends on: T001` both work.
    const stripped = line.replace(/\*\*/g, '')
    const idx = stripped.indexOf(`${key}:`)
    if (idx >= 0) {
      return stripped.slice(idx + key.length + 1).trim()
    }
  }
  return null
}

/**
 * Extract a step block by matching its header (e.g., `Step 3: ...`). The
 * block runs from the header to the next `#### Step ` or `### T` or EOF.
 */
function extractStepBlock(block: string, headerRe: RegExp): string | null {
  const match = block.match(headerRe)
  if (!match || match.index === undefined) return null
  const start = match.index
  const rest = block.slice(start)
  const nextHeader = rest.match(/\n(####\s+Step|\n###\s+T\d|\n##\s+)/)
  const end = nextHeader && nextHeader.index !== undefined ? start + nextHeader.index : block.length
  return block.slice(start, end)
}

function parseRedStep(
  block: string,
  warnings: string[],
): { file: string; testName: string; assertion: string } | undefined {
  const file = matchQuoted(block, /-?\s*File:\s*`([^`]+)`/)
  const name = matchQuoted(block, /-?\s*Test name:\s*`([^`]+)`/)
  const assertion = matchQuoted(block, /-?\s*Assertion:\s*(.+)/)
  if (!file || !name || !assertion) {
    warnings.push('red: incomplete RED step')
    return undefined
  }
  return { file, testName: name, assertion: assertion.trim() }
}

function parseGreenStep(
  block: string,
  warnings: string[],
): { file: string; change: string } | undefined {
  const file = matchQuoted(block, /-?\s*File:\s*`([^`]+)`/)
  const change = matchQuoted(block, /-?\s*Change:\s*(.+)/)
  if (!file || !change) {
    warnings.push('green: incomplete GREEN step')
    return undefined
  }
  return { file, change: change.trim() }
}

function parseVerifyStep(
  block: string,
  warnings: string[],
): { run: string; expectedPass: boolean } | undefined {
  const run = matchQuoted(block, /-?\s*Run:\s*`([^`]+)`/)
  const expected = matchQuoted(block, /-?\s*Expected:\s*(.+)/)
  if (!run) {
    warnings.push('verify: missing Run line')
    return undefined
  }
  return {
    run,
    // PASS implies expectedPass=true; FAIL implies false. Default true if
    // neither keyword found, since "verify GREEN" wants green.
    expectedPass: expected ? !/FAIL/i.test(expected) : true,
  }
}

function parseCommitStep(
  block: string,
  warnings: string[],
): { type: string; scope: string; subject: string } | undefined {
  const messageLine = block.match(/-?\s*Message:\s*`([^`]+)`/)
  if (!messageLine) {
    warnings.push('commit: missing Message line')
    return undefined
  }
  // Conventional commit: <type>(<scope>): <subject>
  const m = messageLine[1].match(/^(\w+)\(([^)]*)\):\s*(.+)$/)
  if (!m) {
    warnings.push(`commit: message does not match conventional format: ${messageLine[1]}`)
    return { type: 'chore', scope: '', subject: messageLine[1] }
  }
  return { type: m[1], scope: m[2], subject: m[3] }
}

/**
 * Return the first capture group of the first match of `re` in `block`.
 */
function matchQuoted(block: string, re: RegExp): string | null {
  const m = block.match(re)
  return m ? m[1] : null
}